import assert from 'node:assert/strict';
import fs from 'node:fs';
import {levels,projection,signature,rules,check,predictionOptions} from './dist/logic.mjs';
import {Scene} from './dist/scene.mjs';
let checks=0;const ok=(condition,message)=>{assert(condition,message);checks++};
for(const l of levels){ok(rules(l.cubes).ok,`${l.title}: valid construction`);ok(check(l.cubes,l.cubes).solved,`${l.title}: target accepted`);ok(!check([],l.cubes).solved,`${l.title}: empty rejected`);for(const v of ['top','front','right']){const choices=predictionOptions(l.cubes,v,3);ok(choices.filter(c=>c.correct).length===1,`${l.title}: one correct prediction`);ok(new Set(choices.map(c=>signature(c.drawing))).size===3,`${l.title}: distinct choices`);ok(signature(choices.find(c=>c.correct).drawing)===signature(projection(l.cubes,v)),`${l.title}: correct prediction agrees`)}}
const cube=[[1,0,2]];ok(projection(cube,'front').filled[0]==='1,3','Front maps width horizontally and height upward');ok(projection(cube,'top').filled[0]==='1,2','Top maps width and depth');ok(projection(cube,'right').filled[0]==='1,3','Right maps back toward screen right');
const joined=projection([[0,0,0],[1,0,0]],'front');ok(!joined.edges.some(e=>e.join(',')==='1,3,1,4'),'No false seam between coplanar cube faces');
const shiftedDepth=projection([[0,0,0],[1,0,1]],'front');ok(shiftedDepth.edges.some(e=>e.join(',')==='1,3,1,4'),'Visible depth step has an edge');
ok(!rules([[0,1,0]]).ok,'Floating cube rejected');ok(!rules([[0,0,0],[2,0,0]]).ok,'Disconnected cubes rejected');ok(!rules([[4,0,0]]).ok,'Out-of-bounds rejected');ok(!rules([[0,0,0],[0,0,0]]).ok,'Duplicate cubes rejected');
const alt=h=>{const out=[];for(let x=0;x<3;x++)for(let z=0;z<3;z++)for(let y=0;y<(x===1&&z===1?h:3);y++)out.push([x,y,z]);return out};ok(alt(1).length!==alt(2).length,'Alternative constructions differ');ok(check(alt(1),alt(2)).solved,'Different valid constructions with the same three drawings accepted');
// A fake canvas exercises projection, face selection, and input math without a browser.
const listeners={};const c=new Proxy({},{get:()=>()=>{}});const canvas={width:0,height:0,getContext:()=>c,getBoundingClientRect:()=>({width:640,height:340,left:0,top:0}),addEventListener:(type,fn)=>listeners[type]=fn,setPointerCapture(){},focus(){}};globalThis.window={devicePixelRatio:1};globalThis.ResizeObserver=class{observe(){}};let edited=null;const scene=new Scene(canvas,{onEdit:(cell,action)=>edited={cell,action},onViewChange(){}});scene.set([[1,0,1]],'add');
for(const view of ['front','top','right','iso']){scene.setView(view);ok(scene.hits.some(h=>!h.floor),'Visible cube faces in '+view);for(const hit of scene.hits)ok(hit.points.flat().every(Number.isFinite),'Finite projected coordinates');}
scene.setView('front');const face=scene.hits.find(h=>!h.floor);ok(face.normal.join(',')==='0,0,1','Front exposes positive Z face');const p=face.points.reduce((a,v)=>[a[0]+v[0]/4,a[1]+v[1]/4],[0,0]);ok(scene.pick(p).cube.join(',')==='1,0,1','Face picking hits cube');listeners.pointerdown({button:0,clientX:p[0],clientY:p[1],pointerId:1});listeners.pointerup({clientX:p[0],clientY:p[1]});ok(edited.cell.join(',')==='1,0,2','Clicking front face adds cube toward viewer');
scene.setView('iso');listeners.pointerdown({button:0,clientX:-1000,clientY:170,pointerId:2});listeners.pointermove({clientX:1640,clientY:170});listeners.pointerup({clientX:1640,clientY:170});ok(scene.q.every(Number.isFinite),'Antipodal arcball drag remains finite');
const html=fs.readFileSync('dist/index.html','utf8');for(const file of ['style.css','app.js','logic.mjs','scene.mjs'])ok(fs.existsSync('dist/'+file),'Asset exists: '+file);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);ok(new Set(ids).size===ids.length,'No duplicate element IDs');ok(!/https?:\/\//.test(html.replace(/data:image\/svg\+xml[^\"]+/g,'')),'No remote runtime resources');
console.log(`${checks} checks passed: puzzle rules, all prediction choices, alternative solutions, orthographic orientation, face picking, arcball stability, and local assets.`);
